name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  BuildImageTest:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USER  }}
    - name: Build worker image
      run: |
        docker pull taccwma/protx-geospatial:latest
        docker build --cache-from taccwma/protx-geospatial:latest .
